-- | End-to-end tests of the example programs. Each query is a regression
-- case: if the interpreter disagrees, the test names the file and goal.
module Examples.ExamplesSpec (tests) where

import Data.Text qualified as T
import Test.Tasty (TestTree, testGroup)
import Test.Tasty.HUnit (assertBool, assertEqual, testCase)

import LambdaProlog.Driver (QueryResult (..), loadFile, runQueryN)
import LambdaProlog.Error (renderError)

tests :: TestTree
tests =
  testGroup
    "examples"
    [ succeeds "lists.mod" "append (1 :: 2 :: nil) (3 :: nil) L"
    , succeeds "lists.mod" "reverse (1 :: 2 :: 3 :: nil) K"
    , succeeds "lists.mod" "length (1 :: 2 :: 3 :: nil) N"
    , succeeds "lists.mod" "nth 1 (10 :: 20 :: 30 :: nil) X"
    , succeeds "lists.mod" "member 2 (1 :: 2 :: 2 :: nil)"
    , nsols "lists.mod" "memb 2 (1 :: 2 :: 2 :: nil)" 2
    , succeeds "lists.mod" "zip (1 :: nil) (2 :: nil) (pr 1 2 :: nil)"
    , succeeds "lists.mod" "assoc 1 2 (pr 1 2 :: pr 3 4 :: nil)"
    , succeeds "lists.mod" "flatten ((1 :: nil) :: (2 :: 3 :: nil) :: nil) L"
    , succeeds "lists.mod" "join (1 :: 2 :: nil) (2 :: 3 :: nil) L"
    , succeeds "tutorial.mod" "append (1 :: nil) (2 :: nil) L"
    , succeeds "tutorial.mod" "edge a b => edge b c => path a c"
    , succeeds "tutorial.mod" "pi x\\ ident x x"
    , succeeds "tutorial.mod" "copy (abs (x\\ x)) M"
    , succeeds "hypothetical.mod" "edge b c => path a c"
    , fails "hypothetical.mod" "path a c"
    , succeeds "hidden_reverse.mod" "reverse (1 :: 2 :: 3 :: nil) K"
    , succeeds "typeinf.mod" "of (abs (y\\ y)) (arrow A A)"
    , succeeds "typeinf.mod" "hastype (abs (y\\ y))"
    , succeeds "hoas_lambda.mod" "eval (abs (x\\ x)) V"
    , succeeds "hoas_lambda.mod" "eval (app (abs (x\\ x)) (abs (y\\ y))) V"
    , succeeds "hoas_lambda.mod" "copy (abs (x\\ x)) M"
    , succeeds "hoas_lambda.mod" "size (abs (x\\ x)) N"
    , succeeds "prenex.mod" "prenex (all (x\\ atom x)) D"
    , succeeds "prenex.mod" "prenex (and (all (x\\ atom x)) (atom a)) D"
    , succeeds "tacticals.mod" "idtac p p"
    , succeeds "tacticals.mod" "ptac p (andgoal q r)"
    , succeeds "tacticals.mod" "then ptac (orelse qtac rtac) p (andgoal truegoal truegoal)"
    , succeeds "maps.mod" "append (1 :: nil) (2 :: nil) L"
    , succeeds "maps.mod" "mappred age (\"bob\" :: \"sue\" :: nil) L"
    , succeeds "maps.mod" "mapfun (x\\ x) (1 :: 2 :: nil) L"
    , succeeds "control.mod" "once true"
    , succeeds "control.mod" "ifte fail fail true"
    , succeeds "nat.mod" "min 3 1 M"
    , succeeds "nat.mod" "even 4"
    , fails "nat.mod" "odd 4"
    , succeeds "nat.mod" "between 1 3 N"
    , succeeds "nat.mod" "abs (~ 4) A"
    , succeeds "sets.mod" "subset (1 :: nil) (1 :: 2 :: nil)"
    , succeeds "sets.mod" "union (1 :: nil) (1 :: 2 :: nil) U"
    , succeeds "assoc.mod" "addassoc 1 2 nil L"
    , succeeds "lists.mod" "same_length (1 :: nil) (2 :: nil)"
    , succeeds "lists.mod" "nextto 1 2 (1 :: 2 :: 3 :: nil)"
    , succeeds "lists.mod" "snoc 3 (1 :: 2 :: nil) L"
    , succeeds "lists.mod" "init (1 :: 2 :: 3 :: nil) L"
    , succeeds "lists.mod" "delete_all 1 (1 :: 2 :: 1 :: nil) L"
    , succeeds "lists.mod" "nub (1 :: 1 :: 2 :: nil) L"
    , succeeds "lists.mod" "permute (1 :: 2 :: nil) (2 :: 1 :: nil)"
    , nsols "lists.mod" "permute (1 :: 2 :: nil) K" 2
    , succeeds "lists.mod" "count 1 (1 :: 2 :: 1 :: nil) N"
    , succeeds "lists.mod" "replicate 3 7 L"
    , succeeds "lists.mod" "sum_list (1 :: 2 :: 3 :: nil) N"
    , succeeds "lists.mod" "max_list (1 :: 3 :: 2 :: nil) N"
    , succeeds "lists.mod" "min_list (1 :: 3 :: 2 :: nil) N"
    , succeeds "lists.mod" "take 2 (1 :: 2 :: 3 :: nil) L"
    , succeeds "lists.mod" "drop 2 (1 :: 2 :: 3 :: nil) L"
    , succeeds "lists.mod" "last (1 :: 2 :: 3 :: nil) X"
    , succeeds "lists.mod" "is_prefix (1 :: nil) (1 :: 2 :: nil)"
    , succeeds "lists.mod" "suffix (2 :: nil) (1 :: 2 :: nil)"
    , succeeds "maps.mod" "filter (x\\ x > 1) (1 :: 2 :: 3 :: nil) L"
    , succeeds "maps.mod" "for_each (x\\ x > 0) (1 :: 2 :: nil)"
    , succeeds "maps.mod" "partition (x\\ x > 1) (1 :: 2 :: 3 :: nil) A B"
    , succeeds "maps.mod" "exists_pred (x\\ x = 2) (1 :: 2 :: 3 :: nil)"
    , fails "maps.mod" "exists_pred (x\\ x = 9) (1 :: 2 :: 3 :: nil)"
    , succeeds "maps.mod" "find (x\\ x > 1) (1 :: 2 :: 3 :: nil) X"
    , succeeds "maps.mod" "map2 (x\\ y\\ z\\ z is x + y) (1 :: 2 :: nil) (10 :: 20 :: nil) L"
    , succeeds "control.mod" "call (true, true)"
    , succeeds "control.mod" "once (true, true)"
    , fails "control.mod" "once (fail, true)"
    , succeeds "control.mod" "ifte true true fail"
    , succeeds "control.mod" "ignore fail"
    , succeeds "nat.mod" "gcd 12 8 D"
    , succeeds "nat.mod" "pow 2 3 N"
    , succeeds "nat.mod" "succ 3 N"
    , succeeds "nat.mod" "sign (~ 4) S"
    , succeeds "nat.mod" "max 3 1 M"
    , succeeds "sets.mod" "difference (1 :: 2 :: 3 :: nil) (2 :: nil) D"
    , succeeds "sets.mod" "disjoint (1 :: nil) (2 :: nil)"
    , fails "sets.mod" "disjoint (1 :: nil) (1 :: 2 :: nil)"
    , succeeds "sets.mod" "insert 1 (2 :: nil) S"
    , succeeds "sets.mod" "card (1 :: 1 :: 2 :: nil) N"
    , succeeds "sets.mod" "seteq (1 :: 2 :: nil) (2 :: 1 :: nil)"
    , succeeds "assoc.mod" "lookup 1 (pr 1 2 :: nil) Y"
    , succeeds "assoc.mod" "update 1 9 (pr 1 2 :: nil) L"
    , succeeds "assoc.mod" "delassoc 1 (pr 1 2 :: pr 3 4 :: nil) L"
    , succeeds "prenex.mod" "nnf (neg (and (atom a) (atom a))) D"
    , succeeds "prenex.mod" "nnf (neg (all (x\\ atom x))) D"
    , succeeds "hoas_lambda.mod" "subst (x\\ x) (abs (y\\ y)) M"
    , succeeds "hoas_lambda.mod" "beta (app (abs (x\\ x)) (abs (y\\ y))) M"
    , succeeds "typeinf.mod" "of (app (abs (x\\ x)) c) i"
    , succeeds "typeinf.mod" "of c i"
    , succeeds "trees.mod" "tmember 2 (node 1 empty (node 2 empty empty))"
    , succeeds "trees.mod" "tsize (node 1 empty empty) N"
    , succeeds "trees.mod" "tflatten (node 2 (node 1 empty empty) empty) L"
    , succeeds "trees.mod" "tmap (x\\ x) (node 1 empty empty) T"
    , succeeds "strings.mod" "strcat \"ab\" \"cd\" S"
    , succeeds "strings.mod" "empty_string \"\""
    , succeeds "lists.mod" "null nil"
    , fails "lists.mod" "null (1 :: nil)"
    , succeeds "lists.mod" "nth1 1 (10 :: 20 :: nil) X"
    , succeeds "lists.mod" "iota 1 3 L"
    , succeeds "lists.mod" "isort (3 :: 1 :: 2 :: nil) K"
    , succeeds "lists.mod" "msort (3 :: 1 :: 4 :: 2 :: nil) K"
    , succeeds "lists.mod" "ordered (1 :: 2 :: 3 :: nil)"
    , fails "lists.mod" "ordered (2 :: 1 :: nil)"
    , succeeds "lists.mod" "palindrome (1 :: 2 :: 1 :: nil)"
    , succeeds "lists.mod" "sublist (2 :: 3 :: nil) (1 :: 2 :: 3 :: 4 :: nil)"
    , succeeds "lists.mod" "product_list (2 :: 3 :: 4 :: nil) N"
    , succeeds "lists.mod" "split_at 2 (1 :: 2 :: 3 :: 4 :: nil) P S"
    , succeeds "lists.mod" "rotate (1 :: 2 :: 3 :: nil) K"
    , succeeds "lists.mod" "intersperse 0 (1 :: 2 :: 3 :: nil) L"
    , succeeds "lists.mod" "replace_nth 1 (1 :: 2 :: 3 :: nil) 9 L"
    , succeeds "lists.mod" "tails (1 :: 2 :: nil) T"
    , succeeds "lists.mod" "inits (1 :: 2 :: nil) I"
    , succeeds "lists.mod" "fst (pr 1 2) X"
    , succeeds "lists.mod" "dappend (pr (1 :: H) H) (pr (2 :: 3 :: T) T) (pr L nil)"
    , succeeds "maps.mod" "qsort (3 :: 1 :: 2 :: nil) K"
    , succeeds "maps.mod" "take_while (x\\ x < 3) (1 :: 2 :: 3 :: nil) L"
    , succeeds "maps.mod" "drop_while (x\\ x < 3) (1 :: 2 :: 3 :: nil) L"
    , succeeds "maps.mod" "foldr_pred add 0 (1 :: 2 :: 3 :: nil) N"
    , succeeds "maps.mod" "senior N"
    , succeeds "maps.mod" "scanl (x\\ y\\ x) 0 (1 :: 2 :: nil) L"
    , succeeds "control.mod" "unless fail true"
    , fails "control.mod" "unless true fail"
    , succeeds "control.mod" "repeat_n 3 true"
    , succeeds "control.mod" "and_then true true"
    , succeeds "control.mod" "or_else fail true"
    , succeeds "nat.mod" "lcm 4 6 Z"
    , succeeds "nat.mod" "factorial 5 K"
    , succeeds "nat.mod" "fib 6 N"
    , succeeds "nat.mod" "divides 3 12"
    , fails "nat.mod" "divides 5 12"
    , succeeds "nat.mod" "coprime 9 4"
    , succeeds "nat.mod" "clamp 0 10 (~ 3) C"
    , succeeds "nat.mod" "square 7 Y"
    , succeeds "nat.mod" "eeval (eplus (elit 2) (etimes (elit 3) (elit 4))) N"
    , nsols "sets.mod" "powerset (1 :: 2 :: nil) P" 4
    , succeeds "sets.mod" "psubset (1 :: nil) (1 :: 2 :: nil)"
    , succeeds "sets.mod" "symdiff (1 :: 2 :: nil) (2 :: 3 :: nil) U"
    , succeeds "sets.mod" "from_list (1 :: 1 :: 2 :: nil) S"
    , succeeds "sets.mod" "add_all (1 :: 2 :: nil) (2 :: nil) S"
    , succeeds "assoc.mod" "lookup1 1 (pr 1 2 :: pr 1 9 :: nil) Y"
    , succeeds "assoc.mod" "has_key 3 (pr 1 2 :: pr 3 4 :: nil)"
    , succeeds "assoc.mod" "from_zip (1 :: 2 :: nil) (10 :: 20 :: nil) B"
    , succeeds "assoc.mod" "dial \"ada\" N"
    , succeeds "assoc.mod" "keys (pr 1 2 :: pr 3 4 :: nil) K"
    , succeeds "trees.mod" "theight (node 1 (node 0 empty empty) empty) N"
    , succeeds "trees.mod" "inorder (node 2 (node 1 empty empty) (node 3 empty empty)) L"
    , succeeds "trees.mod" "preorder (node 2 (node 1 empty empty) (node 3 empty empty)) L"
    , succeeds "trees.mod" "postorder (node 2 (node 1 empty empty) (node 3 empty empty)) L"
    , succeeds "trees.mod" "mirror (node 1 (node 0 empty empty) empty) T"
    , succeeds "trees.mod" "bst_insert 3 empty T"
    , succeeds "trees.mod" "demo_tree T"
    , succeeds "trees.mod" "leaf 4 T"
    , succeeds "strings.mod" "concat_all (\"a\" :: \"b\" :: \"c\" :: nil) S"
    , succeeds "strings.mod" "join_with \",\" (\"a\" :: \"b\" :: \"c\" :: nil) S"
    , succeeds "option.mod" "is_none none"
    , succeeds "option.mod" "is_some (some 3) X"
    , succeeds "option.mod" "from_option 0 none Y"
    , succeeds "option.mod" "from_option 0 (some 4) Y"
    , succeeds "option.mod" "map_option (x\\ x) (some 1) R"
    , succeeds "option.mod" "filter_option (x\\ x > 2) (some 3) (some 3)"
    , succeeds "option.mod" "filter_option (x\\ x > 2) (some 1) none"
    , succeeds "option.mod" "or_else_option none (some 5) (some 5)"
    , succeeds "option.mod" "to_list (some 7) (7 :: nil)"
    , succeeds "option.mod" "from_list_first (1 :: 2 :: nil) (some 1)"
    , succeeds "option.mod" "option_of (x\\ x = 2) X R"
    , succeeds "hoas_lambda.mod" "is_abs (abs (x\\ x))"
    , succeeds "hoas_lambda.mod" "church 0 C"
    , succeeds "hoas_lambda.mod" "church 2 C"
    , succeeds "hoas_lambda.mod" "combinator \"I\" T"
    , succeeds "hoas_lambda.mod" "combinator \"K\" T"
    , succeeds "typeinf.mod" "of true bool"
    , succeeds "typeinf.mod" "of (if true c c) i"
    , succeeds "typeinf.mod" "of (mkpair c true) (prod i bool)"
    , succeeds "typeinf.mod" "of (fst (mkpair c true)) i"
    , succeeds "typeinf.mod" "ident_ty T"
    , succeeds "typeinf.mod" "const_ty i bool"
    , succeeds "typeinf.mod" "hastype (abs (x\\ app x c))"
    , succeeds "prenex.mod" "fsize (and (atom a) (atom b)) N"
    , succeeds "prenex.mod" "is_closed (atom a)"
    , succeeds "prenex.mod" "inst (x\\ atom x) a F"
    , succeeds "prenex.mod" "nnf (iff (atom a) (atom b)) D"
    , succeeds "tacticals.mod" "complete qtac q truegoal"
    , succeeds "tacticals.mod" "try stac q q"
    , succeeds "tacticals.mod" "progress ptac p G"
    , succeeds "tacticals.mod" "first qtac ptac p (andgoal q r)"
    , succeeds "hypothetical.mod" "path a d"
    , succeeds "hypothetical.mod" "cycle3"
    , succeeds "hypothetical.mod" "via_e"
    , succeeds "hypothetical.mod" "(edge d a) => (path b a, !)"
    , succeeds "tutorial.mod" "member 2 (1 :: 2 :: 3 :: nil)"
    , succeeds "tutorial.mod" "reverse (1 :: 2 :: 3 :: nil) K"
    -- STLC showcase
    , succeeds "stlc.mod" "typeof (abs_tm int_ty (x\\ x)) (arr_ty int_ty int_ty)"
    , succeeds "stlc.mod" "eval (app_tm (abs_tm int_ty (x\\ x)) (int_tm 42)) (int_tm 42)"
    , succeeds "stlc.mod" "preserves (app_tm (abs_tm int_ty (x\\ x)) (int_tm 42))"
    , succeeds "stlc.mod" "eval (fst_tm (pair_tm (int_tm 10) true_tm)) (int_tm 10)"
    , succeeds "stlc.mod" "eval (case_tm (inl_tm bool_ty (int_tm 7)) (x\\ x) (y\\ int_tm 0)) (int_tm 7)"
    -- de Bruijn conversion
    , succeeds "debruijn.mod" "hoas_to_debruijn (habs (x\\ x)) (dlam (dvar 0))"
    , succeeds "debruijn.mod" "hoas_to_debruijn (habs (x\\ habs (y\\ x))) (dlam (dlam (dvar 1)))"
    , succeeds "debruijn.mod" "debruijn_to_hoas (dlam (dvar 0)) H"
    , succeeds "debruijn.mod" "d_eval (dapp (dlam (dvar 0)) (dlam (dlam (dvar 1)))) (dlam (dlam (dvar 1)))"
    -- Interpreter with hypothetical scoping & shadowing
    , succeeds "interp_scope.mod" "exec_res (slet \"x\" (elit 10) (slet \"y\" (elit 20) (sresult (eadd (evar \"x\") (evar \"y\"))))) 30"
    , succeeds "interp_scope.mod" "exec_res (slet \"x\" (elit 10) (sseq (slet \"x\" (elit 5) (sresult (emul (evar \"x\") (elit 2)))) (sresult (evar \"x\")))) 10"
    -- CPS & ANF transformations
    , succeeds "cps_anf.mod" "to_anf (plus_e (cst 1) (cst 2)) A"
    , succeeds "cps_anf.mod" "to_cps (plus_e (cst 10) (cst 20)) C"
    -- Modal logic & Kripke semantics
    , succeeds "modal_logic.mod" "(acc w0 w1, val w1 \"p\") => sat w0 (dia (atom \"p\"))"
    , succeeds "modal_logic.mod" "test_axiom_k w0 (atom \"p\") (atom \"q\")"
    , succeeds "modal_logic.mod" "test_axiom_t w0 (atom \"p\")"
    -- Definite clause grammars
    , succeeds "dcg.mod" "parse_sentence (\"the\" :: \"cat\" :: \"sleeps\" :: nil)"
    , fails "dcg.mod" "parse_sentence (\"the\" :: \"cats\" :: \"sleeps\" :: nil)"
    , succeeds "dcg.mod" "parse_and_eval (\"2\" :: \"+\" :: \"3\" :: \"*\" :: \"4\" :: nil) 14"
    -- Coinduction & bisimulation
    , succeeds "coinduction.mod" "bisimilar s_zeroes (s_cons 0 s_zeroes)"
    , succeeds "coinduction.mod" "take_stream 4 s_alt01 (0 :: 1 :: 0 :: 1 :: nil)"
    , succeeds "coinduction.mod" "state_bisim p0 q0"
    -- HOPU & symbolic differentiation
    , succeeds "hopu_meta.mod" "diff_and_simp (x\\ times_m (num 3) x) (x\\ num 3)"
    , succeeds "hopu_meta.mod" "diff_and_simp (x\\ plus_m (times_m x x) (num 5)) DF"
    -- Result & Either standard library
    , succeeds "result.mod" "map_ok (x\\ y\\ y is x + 1) (ok 5) (ok 6)"
    , succeeds "result.mod" "and_then (x\\ r\\ sigma y\\ y is x * 2, r = ok y) (ok 10) (ok 20)"
    , succeeds "result.mod" "partition_results (ok 1 :: err \"fail\" :: ok 3 :: nil) (1 :: 3 :: nil) (\"fail\" :: nil)"
    , succeeds "result.mod" "sequence_results (ok 1 :: ok 2 :: nil) (ok (1 :: 2 :: nil))"
    -- Natural deduction & proof terms
    , succeeds "natural_deduction.mod" "proves (p_imp (p_atom \"A\") (p_atom \"A\")) (lam_p (p_atom \"A\") (x\\ x))"
    , succeeds "natural_deduction.mod" "has_proof (lam_p (p_and (p_atom \"a\") (p_atom \"b\")) (p\\ pair_p (snd_p p) (fst_p p))) (p_imp (p_and (p_atom \"a\") (p_atom \"b\")) (p_and (p_atom \"b\") (p_atom \"a\")))"
    -- First-order logic prover
    , succeeds "fol_prover.mod" "prove (f_imp (f_all (x\\ f_atom \"P\" (x :: nil))) (f_atom \"P\" (_ :: nil)))"
    , succeeds "fol_prover.mod" "prove (f_imp (f_all (x\\ f_and (f_atom \"P\" (x :: nil)) (f_atom \"Q\" (x :: nil)))) (f_and (f_all (x\\ f_atom \"P\" (x :: nil))) (f_all (x\\ f_atom \"Q\" (x :: nil)))))"
    -- Combinatory logic & bracket abstraction
    , succeeds "combinators.mod" "bracket (x\\ x) c_i"
    , succeeds "combinators.mod" "bracket (x\\ c_i) (c_app c_k c_i)"
    , succeeds "combinators.mod" "reduce (c_app c_i (c_app (c_app c_k c_s) c_i)) c_s"
    -- Enriched existing modules
    , succeeds "typeinf.mod" "of unit_val unit_t"
    , succeeds "typeinf.mod" "of (inl_tm bool c) (sum i bool)"
    , succeeds "hoas_lambda.mod" "nf (app (abs (x\\ app (abs (y\\ y)) x)) (abs (z\\ z))) (abs (z\\ z))"
    , succeeds "hoas_lambda.mod" "alpha_equiv (abs (x\\ x)) (abs (y\\ y))"
    , succeeds "lists.mod" "intercalate (0 :: nil) ((1 :: nil) :: (2 :: nil) :: (3 :: nil) :: nil) (1 :: 0 :: 2 :: 0 :: 3 :: nil)"
    , succeeds "lists.mod" "chunks_of 2 (1 :: 2 :: 3 :: 4 :: nil) ((1 :: 2 :: nil) :: (3 :: 4 :: nil) :: nil)"
    , succeeds "option.mod" "flatten_option (some (some 42)) (some 42)"
    , succeeds "option.mod" "cat_options (some 1 :: none :: some 3 :: nil) (1 :: 3 :: nil)"
    , succeeds "hypothetical.mod" "safe_path a d"
    , fails "hypothetical.mod" "(blocked a b) => safe_path a d"
    ]
  where
    succeeds file q = testCase (file ++ " ⊢ " ++ q) $ do
      sols <- runExN 1 file q
      assertBool "expected success" (not (null sols))
    fails file q = testCase (file ++ " ⊬ " ++ q) $ do
      sols <- runExN 1 file q
      assertBool "expected failure" (null sols)
    nsols file q n = testCase (file ++ " # " ++ q) $ do
      sols <- runExN (n + 1) file q
      assertEqual "solution count" n (length sols)

    runExN n file q = do
      r <- loadFile ["examples", "."] ("examples/" ++ file)
      case r of
        Left e -> fail (T.unpack (renderError e))
        Right ld ->
          case runQueryN ld n (T.pack q) of
            Left e -> fail (T.unpack (renderError e))
            Right (QueryResult _ sols) -> pure sols

